"use client";

import Image from "next/image";
import Link from "next/link";
import type { Prisma } from "@prisma/client";
import { useCart } from "@/shared/providers/CartProvider";
import { useFavorites } from "@/shared/providers/FavoritesProvider";

type CatalogProduct = Prisma.ProductGetPayload<{ include: { category: true } }>;

export function DesktopBoutiqueResults({ products }: { products: CatalogProduct[] }) {
  const { addToCart } = useCart();
  const { isFavorite, toggleFavorite } = useFavorites();
  return <div className="flex gap-8"><div className="flex-1 grid grid-cols-3 gap-6">{products.length === 0 ? <div className="col-span-3 py-20 text-center text-[#a89b82]">Aucun produit trouvé.</div> : products.map((product) => <div key={product.id} className="group border border-[#d4af37]/30 rounded-2xl p-4 bg-[#0c0a07] hover:border-[#d4af37]/60 transition-colors"><Link href={`/produit/${product.id}`} className="block"><div className="relative h-[220px] rounded-xl overflow-hidden mb-4 bg-[#1a1a1a]"><Image src={product.image ?? "/images/product_1.jpg"} alt={product.name} fill sizes="(max-width: 1200px) 33vw, 25vw" className="object-cover group-hover:scale-105 transition-transform duration-500" />{product.isNew && <span className="absolute top-3 left-3 bg-[#0a0a0a]/80 backdrop-blur border border-[#d4af37]/50 text-[#d4af37] text-[9px] font-bold px-2 py-1 rounded uppercase tracking-wider">NOUVEAU</span>}<button onClick={(event) => { event.preventDefault(); toggleFavorite(product.id, product.name); }} className="absolute top-3 right-3 w-8 h-8 rounded-full bg-[#0a0a0a]/80 backdrop-blur border border-[#d4af37]/30 flex items-center justify-center text-[#a89b82] hover:text-[#d4af37] transition-colors" aria-label="Ajouter aux favoris"><span aria-hidden="true">{isFavorite(product.id) ? "♥" : "♡"}</span></button></div><h4 className="font-serif text-[#e8e1d3] text-sm mb-1">{product.name}</h4><p className="text-[#a89b82] text-[10px] mb-3 capitalize">{product.category.name}</p></Link><div className="flex items-center justify-between"><p className="text-[#d4af37] font-semibold text-sm">{product.price.toLocaleString("fr-FR")} FCFA</p><button onClick={() => addToCart({ id: product.id, name: product.name, price: product.price, image: product.image ?? "/images/product_1.jpg" })} className="text-[10px] font-medium text-[#0a0a0a] bg-[#d4af37] hover:bg-[#e8c547] px-3 py-1.5 rounded-lg flex items-center gap-1 transition-colors">+ Ajouter</button></div></div>)}</div><aside className="w-[300px] shrink-0 border border-[#d4af37]/30 rounded-2xl p-6 bg-[#0c0a07] flex flex-col h-fit sticky top-0"><div className="w-12 h-12 rounded-full border border-[#d4af37] flex items-center justify-center text-[#d4af37] mb-4 bg-[#d4af37]/10">+</div><h4 className="font-serif text-lg text-[#e8e1d3] mb-2">Livraison rapide partout au Sénégal</h4><p className="text-[#a89b82] text-xs leading-relaxed mb-6">Paiement à la livraison ou Wave / Orange Money</p><button className="mt-auto w-full flex items-center justify-between text-sm text-[#e8e1d3] group border-t border-[#d4af37]/20 pt-4"><span>Voir les conditions</span><span className="text-[#d4af37] group-hover:translate-x-1 transition-transform" aria-hidden="true">-&gt;</span></button></aside></div>;
}
