import Image from "next/image";
import Link from "next/link";
import { ROUTES } from "@/shared/constants/config";

export function DesktopTrackingAside() {
  return <aside className="w-[380px] shrink-0 overflow-y-auto px-8 py-8 flex flex-col gap-6 bg-[#0a0a0a]">
    <div className="border border-[#d4af37]/30 rounded-2xl p-6 bg-[#0c0a07]"><h3 className="font-serif text-[#e8e1d3] text-xl mb-1">Besoin d&apos;aide ?</h3><p className="text-[#a89b82] text-[13px] mb-6">Notre équipe est là pour vous accompagner.</p><div className="flex flex-col gap-5">{[["+221 77 123 45 67", "Lun - Sam : 9h - 20h"], ["contact@bushra.sn", "Réponse sous 24h"], ["WhatsApp", "Disponible de 9h à 22h"]].map(([title, detail]) => <div key={title} className="flex items-center justify-between border-b border-[#d4af37]/10 pb-5 last:border-b-0 last:pb-0"><div><p className="text-[#e8e1d3] text-sm mb-0.5">{title}</p><p className="text-[#a89b82] text-[11px]">{detail}</p></div><span className="text-[#d4af37]" aria-hidden="true">-&gt;</span></div>)}</div></div>
    <div className="relative border border-[#d4af37]/30 rounded-2xl overflow-hidden h-[240px] flex flex-col justify-end p-6 bg-[#0c0a07]"><div className="absolute inset-0 z-0"><Image src="/images/hero_censer.jpg" alt="Experience unique" fill sizes="300px" className="object-cover opacity-60 mix-blend-overlay" /><div className="absolute inset-0 bg-gradient-to-t from-[#0a0a0a] via-[#0a0a0a]/80 to-transparent" /></div><div className="relative z-10"><h4 className="font-serif text-[#d4af37] text-2xl mb-2 leading-tight">Une expérience<br />unique</h4><p className="text-[#e8e1d3] text-xs mb-4">Des parfums d&apos;exception<br />pour chaque instant.</p><Link href={ROUTES.shop} className="inline-flex items-center gap-2 bg-[#e8c547] hover:bg-[#d4af37] text-[#0a0a0a] font-semibold px-5 py-2.5 rounded-xl transition-colors text-xs">Découvrir la boutique</Link></div></div>
    <div className="border border-[#d4af37]/30 rounded-2xl p-6 bg-[#0c0a07]"><p className="text-[#e8e1d3] font-medium text-sm mb-6">Pourquoi commander chez Bushra ?</p><div className="flex gap-2">{[["Livraison rapide", "Sénégal"], ["Paiement sécurisé", "Orange Money"], ["Produits authentiques", "100% originaux"]].map(([title, detail]) => <div key={title} className="flex flex-col items-center text-center flex-1 px-2"><p className="text-[#e8e1d3] text-[9px] font-medium leading-tight mb-1">{title}</p><p className="text-[#a89b82] text-[8px]">{detail}</p></div>)}</div></div>
  </aside>;
}
